# Generated by Django 4.2.23 on 2025-08-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('age', models.PositiveIntegerField()),
                ('breed', models.CharField(max_length=120)),
                ('type', models.CharField(max_length=20)),
                ('health_status', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pets/')),
                ('available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
