# Generated by Django 4.2.23 on 2025-08-20 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='shelter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['type', 'breed'], name='pets_pet_type_e2d959_idx'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['available'], name='pets_pet_availab_9af87c_idx'),
        ),
    ]
