# Generated by Django 4.2.23 on 2025-08-31 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userz', '0002_auto_20250831_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
